deb_app/config/routes.rb
Rails.application.routes.draw do

  #get 'password_resets/new'

  #get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/nextMonth',  to: 'showtimes#arrow_ahead_month'
  resources :users do
    member do
      get :following, :followers
    end
  end   
  #resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :showtimes
end

deb_app/app/models/showtime.rb
class Showtime < ApplicationRecord
  belongs_to :user
  default_scope -> { order(show_datetime: :asc) }
  attr_accessor :showtime_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX }
  validates :org, presence: true, length: { maximum: 50} 
  validates :town, presence: true, length: { maximum: 30 }
  validates :phone, presence: true, numericality: { only_integer: true }, length: { is: 10}
  validates :name, presence: true, length: { maximum: 30 }
  validates :street, presence: true, length: { maximum: 50 }
  validates :show_datetime, presence: true
                                    
  # Returns the hash digest of the given string.
  def Showtime.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def Showtime.new_token
    SecureRandom.urlsafe_base64
  end
  
  def send_activation_email(brand_new) 
    ShowMailer.show_activation(brand_new).deliver_now
  end
  
  def send_reset_email(new, prev, org)
    ShowMailer.show_reset(new, prev, org).deliver_now
  end 
  
  def format_for_mailer
    
  end  
  
  
end

deb_app/app/controllers/showtimes_controller.rb
require 'date'
require 'active_support/core_ext/numeric/time.rb'


class ShowtimesController < ApplicationController
  before_action :set_showtime, only: [:show, :edit, :update, :destroy]

  # GET /showtimes
  # GET /showtimes.json
  def index
    if !current_user 
      redirect_to root_url #failed test so changed this
    elsif current_user && !current_user.admin?
      @showtimes = Showtime.where(email: current_user.email)
    elsif current_user.admin?
      @showtimes = Showtime.all
    end
  end
  # GET /showtimes/1
  # GET /showtimes/1.json
  def show
    @showtime = Showtime.find(params[:id])
    @showtime.show_datetime_end = DateTime.new(@showtime.show_datetime.strftime("%Y").to_i, @showtime.show_datetime.strftime("%m").to_i, @showtime.show_datetime.strftime("%d").to_i, @showtime.show_datetime.strftime("%H").to_i + 1, @showtime.show_datetime.strftime("%M").to_i )
    @times = avail_times(@showtime)
  end

  # This method called from showtimes_calendar  GET /showtimes/new
  def new
    @showtime = Showtime.new(showtime_params)
    @day = @showtime.day
    # @showtime.month = params[:month_pass]
    # @showtime.day = params[:day_pass]
    # @showtime.year = params[:year_pass]
    @showtime.show_datetime = DateTime.new(@showtime.year.to_i, @showtime.month.to_i, @showtime.day.to_i, 0, 0)
    
    @times = avail_times(@showtime)
    @times_display = avail_times_to_ampm(@times)
    @hours_avail_on_view = @times_display.zip(@times)
    if current_user
      temp_showtime = Showtime.where(email: current_user.email).last
      if temp_showtime
        @showtime.org = temp_showtime.org
        @showtime.town = temp_showtime.town
        @showtime.street = temp_showtime.street
        @showtime.name = temp_showtime.name
        @showtime.email = temp_showtime.email
        @showtime.phone = temp_showtime.phone
      end
    end 
  end

  # GET /showtimes/1/edit
  def edit
    @times = avail_times(@showtime)
    @times_display = avail_times_to_ampm(@times)
    @hours_avail_on_view = @times_display.zip(@times) 
    @showtime.show_datetime_end = DateTime.new(@showtime.show_datetime.strftime("%Y").to_i, @showtime.show_datetime.strftime("%m").to_i, @showtime.show_datetime.strftime("%d").to_i, @showtime.show_datetime.strftime("%H").to_i + 1, @showtime.show_datetime.strftime("%M").to_i)
      
  end

  # POST /showtimes
  # POST /showtimes.json
  
  def create
    if current_user
      @showtime = current_user.showtimes.new(showtime_params)
    else
      user = User.find_by(name: "non login")
      @showtime = user.showtimes.new(showtime_params)
    end 
    @showtime.update_attribute(:show_datetime, @showtime.show_datetime.change(hour: @showtime.time, min: @showtime.duration))
    @showtime.show_datetime_end = DateTime.new(@showtime.show_datetime.strftime("%Y").to_i, @showtime.show_datetime.strftime("%m").to_i, @showtime.show_datetime.strftime("%d").to_i, @showtime.show_datetime.strftime("%H").to_i + 1, @showtime.show_datetime.strftime("%M").to_i)
    @current_day = @showtime.show_datetime.strftime("%d").to_i
    @times = avail_times(@showtime)
    @times_display = avail_times_to_ampm(@times)
    @hours_avail_on_view = @times_display.zip(@times)
    if available_time?(@showtime)
      respond_to do |format|
        if @showtime.save
          @showtime.send_activation_email(@showtime)
          flash[:success] = "Showtime was successfully created" 
          format.html { redirect_to @showtime } #, notice: 'Showtime was successfully created.'
          format.json { render :show, status: :created, location: @showtime }
        else
          format.html { render :new }
          format.json { render json: @showtime.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        flash[:warning] = "Showtime was not successfully created" 
        format.html { render :new } #, notice: 'Showtime was not successfully created.'
        format.json { render json: @showtime.errors, status: :unprocessable_entity }
      end  
    end  
  end

  # PATCH/PUT /showtimes/1
  # PATCH/PUT /showtimes/1.json
  def update
    @org_send = @showtime.org
    # @showtime = Showtime.find(params[:id])
    @altered_show_create = DateTime.new(@showtime.show_datetime.strftime("%Y").to_i, @showtime.show_datetime.strftime("%m").to_i, @showtime.show_datetime.strftime("%d").to_i, @showtime.show_datetime.strftime("%H").to_i , @showtime.show_datetime.strftime("%M").to_i)
    @altered_show = @altered_show_create.strftime("%m/%d/%Y at %I:%M%p")
    @current_day = @showtime.show_datetime.strftime("%d").to_i
    @showtime.update_attribute(:day, @current_day)
    @times = avail_times(@showtime) 
    @times_display = avail_times_to_ampm(@times)
    @hours_avail_on_view = @times_display.zip(@times)
    @showtime.update(showtime_params)
    @showtime.update_attribute(:show_datetime, @showtime.show_datetime.change(hour: @showtime.time, min: @showtime.duration))
    @current_day = @showtime.show_datetime.strftime("%d").to_i
    
    if available_time?(@showtime)
      respond_to do |format|
        if @showtime.save #update(showtime_params)
          @showtime.update_attribute(:show_datetime, @showtime.show_datetime.change(hour: @showtime.time, min: @showtime.duration))
          @showtime.show_datetime_end = DateTime.new(@showtime.show_datetime.strftime("%Y").to_i, @showtime.show_datetime.strftime("%m").to_i, @showtime.show_datetime.strftime("%d").to_i, @showtime.show_datetime.strftime("%H").to_i + 1, @showtime.show_datetime.strftime("%M").to_i)
          @times = avail_times(@showtime)
          @showtime.send_reset_email(@showtime, @altered_show_create, @org_send)
          flash[:success] = "Showtime was successfully updated" 
          format.html { redirect_to @showtime} #, notice: 'Showtime was successfully updated.' }
          format.json { render :show, status: :ok, location: @showtime }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @showtime.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        @times = avail_times(@showtime) 
        flash[:success] = "Showtime was not successfully created" 
        format.html { render :new } #, notice: 'Showtime not was successfully created.'
        format.json { render json: @showtime.errors, status: :unprocessable_entity }
      end 
    end  
  end

  # DELETE /showtimes/1
  # DELETE /showtimes/1.json
  def destroy
    @org_send = @showtime.org
    @showtime.send_reset_email(@showtime, @showtime, @org_send)
    @showtime.destroy
    respond_to do |format|
      format.html { redirect_to showtimes_url, notice: 'Showtime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def avail_times(show)
     
      @today_shows = Showtime.where(day: show.day)
      times_avail_temp = []
      times_used = []
      if @today_shows != nil
        @today_shows.each do |i|
            if show.id != i.id         #consider the time that the user just selected as still available
              times_used << i.show_datetime.strftime("%H").to_i
              times_used << i.show_datetime.strftime("%H").to_i + 1
              times_used << i.show_datetime.strftime("%H").to_i + 2
            end  
        end
        (9..16).each do |j|
          if !times_used.include?(j) && !times_used.include?(j + 1) && !times_used.include?(j + 2) 
            times_avail_temp << j
          end  
        end  
      else
        times_avail_temp = [ 9,10,11,12,13,14,15,16]
      end  
      return times_avail_temp
  end
  
  def available_time?(shown)
        times_avail2 = avail_times(shown)
        if times_avail2.include?(shown.show_datetime.strftime("%H").to_i)
          return true
        else
          return false
        end
  end
  
  def avail_times_to_ampm(t_array)
    ampm_avail = []
    t_array.each do |k|
      if k < 12
        ampm_avail << "#{k}AM "
      elsif k == 12
        ampm_avail << "12PM "
      else
        ampm_avail << "#{k%12}PM "
      end 
    end
    return ampm_avail
  end   

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_showtime
        @showtime = Showtime.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def showtime_params
        params.require(:showtime).permit(:year, :org, :town, :street, :name, :email, :phone, :month, :day, :time, :duration, :show_datetime, :radio_time, :show_datetime_end, :been_update, :pic, :content)
      end
      
      
    
    
end

deb_app/app/helpers/showtimes_helper.rb
module ShowtimesHelper
   
end

deb_app/app/views/showtimes/_calendar.html.erb
<% 

monthNum = @current_month.mon
year_now = @current_month.year
date = Date.new(year_now,1,1) 
thisDate = date >> monthNum - 1  # get date of first day of current month/year
 %>
<div class="col-md-4 col-md-offset-0">
<% 1.times do |i| 
nextMon = @current_month >> i %>
<table border="2px" class="table-condensed" >
  <tr>
    <td colspan="7">Select A Date For Your Show</td>
  </tr>
  <tr>
    <td colspan="1"><%= link_to '<', root_path(passYear: (@current_month.month == 1 ? -1 : 0) + @current_month.year, passMonth: (@current_month.month == 1 ? 12 : @current_month.month - 1)), class: 'link-to-text-color' %></td>
    <td colspan="5" align="center"><%= nextMon.strftime("%B, %Y") %></td>
    <td colspan="1"><%= link_to '>', root_path(passYear: (@current_month.month == 12 ? 1 : 0) + @current_month.year, passMonth: (@current_month.month % 12 + 1)), class: 'link-to-text-color' %></td>
  </tr>
  <tr><th>Su</th>
      <th>M</th>
      <th>T</th>
      <th>W</th>
      <th>Th</th>
      <th>F</th>
      <th>Sa</th>
  </tr>
  
  <tr>
    <% dayAt = nextMon %>
    <% j = (nextMon.cwday)%7 %>
    <% j.times do  %>
    <td>-</td>
    <% end %>
    <% k = 7 - j %>
    <% k.times do |dayNum| %>
      
      <% dayWM = dayAt.strftime("%A %B %-d, %Y") %>
      <% dayPass = dayAt.strftime("%d") %>
      <% yearPass = dayAt.strftime("%Y") %>
      <% tempMonth = dayAt.strftime("%m") %>
      
      <!--<td><%= link_to "#{dayAt.mday}", new_showtime_path( day_pass: "#{dayPass}",year_pass: "#{yearPass}",dayHidden: "#{dayWM}", month_pass: "#{tempMonth}"), class: 'link-to-text-color' %></td>-->
      <td><%= link_to "#{dayAt.mday}", new_showtime_path( :showtime => {:day => "#{dayPass}",:year => "#{yearPass}", :month => "#{tempMonth}"}), class: 'link-to-text-color' %></td>
      <% dayAt = dayAt + 1 %>
    <% end %>
  </tr>
  
  <% 5.times do %>
  <tr>
    
  <% 7.times do |n|  %>
    
    <% break if dayAt.mday == 1 %>
    
    <% dayWM = dayAt.strftime("%A %B %-d, %Y") %>
    <% tempMonth = dayAt.strftime("%m") %>
    <% dayPass = dayAt.strftime("%d") %>
    <% yearPass = dayAt.strftime("%Y") %>
    
    
    <!--<td><%= link_to "#{dayAt.mday}", new_showtime_path(day_pass: "#{dayPass}",year_pass: "#{yearPass}",dayHidden: "#{dayWM}", month_pass: "#{tempMonth}"), class: 'link-to-text-color' %></td>-->
    <td><%= link_to "#{dayAt.mday}", new_showtime_path( :showtime => {:day => "#{dayPass}",:year => "#{yearPass}", :month => "#{tempMonth}"}), class: 'link-to-text-color' %></td>
    
    <% dayAt = dayAt + 1  %>
      <% if dayAt.mday == 1 %>
      <% (6 - n).times do |x| %>
      <td>-</td>
      <% end %>
      <% end %>
  <% end %>  
  </tr>
  <% end %>
  
</table>

<% end %>

</div>
<%= yield %>

deb_app/app/views/showtimes/_form.html.erb
<% provide(:title, 'Date') %>
<% provide(:button_text, 'Book Your Show') %>

<%= form_with(model: showtime, local: true) do |form| %>
  <% if showtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(showtime.errors.count, "error") %> prohibited this showtime from being saved:</h2>

      <ul>
      <% showtime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row" >
  <% if !@times_display.empty? %>
    <div class="col-md-6 col-md-offset-1">
    <%= form.datetime_select(:show_datetime, {:order => [:year, :month, :day ],:discard_hour => true }, {:style => 'color:blue; font-size: 20px; display: inline;'}) %>
    </div>
    <div class="col-md-3" style="font-size: 20px; display: inline; margin-left: -50px;" >
      <%= form.select(:time, options_for_select(@hours_avail_on_view, prompt: "hour")) %>
    </div> 
    <div class="col-md-2" style="font-size: 20px; display: inline; margin-left: -230px">
      <%= form.select(:duration, options_for_select([["00",00],["15", 15], ["30", 30],["45", 45]], 0), prompt: "minute") %>
    </div>  
  <% end %>
</div>



<div class="row">
  <div class="col-md-4 col-md-offset-2">
  <div class="field">
    <%= form.label :org, "Organization" %>
    <%= form.text_field :org, class: 'form-control' %>
  </div>
    <%= form.hidden_field :month, :value => @showtime.month %>
    <%= form.hidden_field :day, :value => @showtime.day %>
    <%= form.hidden_field :year, :value => @showtime.year %>
  <div class="field">
    <%= form.label :town %>
    <%= form.text_field :town, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street, class: 'form-control' %>
  </div>
  </div>

  <div class="col-md-6">
  <div class="field">
    <%= form.label :name, 'Contact Name' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control', id: :showtime_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.telephone_field :phone, class: 'form-control' %>
    <!--<%= form.text_field :phone, id: :showtime_phone %>-->
  </div>
  </div>
</div>



<div class="row">    
  <div class="col-md-4 col-md-offset-2">
    <div>
    <strong>Enter a Picture/Comment if you like</strong>
    </div>
    <div class="field">
      <%= form.text_area :content, placeholder: "The show must go on..." %>
      <span class="pic">
        <%= form.file_field :pic, accept: 'image/jpeg,image/gif,image/png' %>
        <script type="text/javascript">
        $('#showtime_pic').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
          alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
        });
        </script> 
      </span>
    </div>
  </div>
  
  
  <div class="col-md-6">
    <div class="actions">
      <%= form.submit yield(:button_text), class: "btn btn-primary"  %>
    </div>
  </div> 
</div>

<% end %>

deb_app/app/views/showtimes/edit.html.erb
  <div> 
    <h1 >Showtime-<%= @showtime.show_datetime.strftime("%A %B %-d, %Y") %> </h1>
    <h2><%= @showtime.show_datetime.strftime("%l:%M %p") %> - <%= @showtime.show_datetime_end.strftime("%l:%M %p") %></h2>
    <h2>Times Available Today</h2>
    <h2>
      <% @times_display.each do |i| %>
        <span><%= i %> </span>
      <% end %>
    </h2>
    
    <%= render 'form', showtime: @showtime %>
    
    <%= link_to 'Show', @showtime %> |
    <%= link_to 'Back', root_path %>
  </div>
  
  

    

deb_app/app/views/showtimes/index.html.erb
<div style="min-height: 500px;">
<p id="notice"><%= notice %></p>

<h1>Showtimes</h1>

<table border="2px" class="table-condensed">
  <thead>
    <tr>
      <th>Org</th>
      <th>Town</th>
      <th>Street</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Month</th>
      <th>Day</th>
      <th>Time</th>
      <th>Pic</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @showtimes.each do |showtime| %>
      <tr>
        <td><%= showtime.org %></td>
        <td><%= showtime.town %></td>
        <td><%= showtime.street %></td>
        <td><%= showtime.name %></td>
        <td><%= showtime.email %></td>
        <td><%= showtime.phone %></td>
        <td><%= showtime.month %></td>
        <td><%= showtime.show_datetime.strftime("%d") %></td>
        <td><%= showtime.show_datetime.strftime("%H") %>:<%= showtime.show_datetime.strftime("%M") %></td>
        <td><%= showtime.pic %></td>
        <td><%= showtime.content %></td>
        <% if current_user %>
        <td><%= link_to 'Show', showtime %></td>
        <td><%= link_to 'Edit', edit_showtime_path(showtime) %></td>
        <td><%= link_to 'Destroy', showtime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div>
<%= link_to 'New Showtime', new_showtime_path %>
</div>
</div>

deb_app/app/views/showtimes/new.html.erb
<h1>New Showtime: <%= @showtime.show_datetime.strftime("%A, %B %-d, %Y") %></h1>
<h2>Times Available This Day</h2>
    
    <% if @times_display.empty? %>
        <h2>We're sorry. This day is booked. Please click <%= link_to "here", root_url, style: "color:blue" %> </h2>
    <% else %>
        <h2>
        <% @times_display.each do |i| %>
            <span><%= i %> </span>
        <% end %>
       </h2>
        <%= render 'form', showtime: @showtime %>
    <% end %> 

<%= link_to 'Back', showtimes_path %>

deb_app/app/views/showtimes/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @showtime.show_datetime.strftime("%A %B %-d, %Y") %></h1>
<h2><%= @showtime.show_datetime.strftime("%l:%M %p") %> - <%= @showtime.show_datetime_end.strftime("%l:%M %p") %></h2>

<div class="row">
  <div class="col-md-3 col-md-offset-3">
    <p>
      <strong>Org:</strong>
      <%= @showtime.org %>
    </p>
    
    <p>
      <strong>Town:</strong>
      <%= @showtime.town %>
    </p>
    
    <p>
      <strong>Street:</strong>
      <%= @showtime.street %>
    </p>
  </div>
 
  <div class="col-md-6">
    <p>
      <strong>Name:</strong>
      <%= @showtime.name %>
    </p>
    
    <p>
      <strong>Email:</strong>
      <%= @showtime.email %>
    </p>
    
    <p>
      <strong>Phone:</strong>
      <%= @showtime.phone %>
    </p>
  </div>
</div>  
<div class="col-md-3 col-md-offset-3">
    
  <p>
    <strong>Pic:</strong>
    <%= @showtime.pic %>
  </p>
  
  <p>
    <strong>Content:</strong>
    <%= @showtime.content %>
  </p>
  

<%= link_to 'Edit/Update', edit_showtime_path(@showtime), class:"link-to-text-color" %> |
<%= link_to 'Back', showtimes_path, class:"link-to-text-color" %>
</div>